export const DEFAULT_MENU = [
  // —— Pies ——
  { id: "p01", name: "Steak Pie", price: 7.9, cat: "Pies" },
  { id: "p02", name: "Steak & Cheese", price: 7.9, cat: "Pies" },
  { id: "p03", name: "Steak & Pepper", price: 7.9, cat: "Pies" },
  { id: "p04", name: "Steak Mushroom", price: 7.9, cat: "Pies" },
  { id: "p05", name: "Steak Bacon Cheese", price: 7.9, cat: "Pies" },
  { id: "p06", name: "Steak Cheese Jalapeño", price: 7.9, cat: "Pies" },
  { id: "p07", name: "Steak Double Cheese", price: 8.7, cat: "Pies" },
  { id: "p08", name: "Mince & Cheese", price: 7.9, cat: "Pies" },
  { id: "p09", name: "Mince Double Cheese", price: 8.7, cat: "Pies" },
  { id: "p10", name: "Mince & Pepper", price: 7.9, cat: "Pies" },
  { id: "p11", name: "Chicken Mushroom", price: 7.9, cat: "Pies" },
  { id: "p12", name: "Chicken & Cheese", price: 7.9, cat: "Pies" },
  { id: "p13", name: "Butter Chicken", price: 7.9, cat: "Pies" },
  { id: "p14", name: "Bacon & Egg Pie", price: 7.9, cat: "Pies" },
  { id: "p15", name: "Double Happy", price: 8.5, cat: "Pies" },
  { id: "p16", name: "Small Mince Pie", price: 3.8, cat: "Pies" },
  { id: "p17", name: "Small Mince Potato", price: 3.8, cat: "Pies" },
  { id: "p18", name: "Sausage Roll", price: 6.0, cat: "Pies" },
  // —— Sandwiches ——
  { id: "s01", name: "Mixed Sandwiches", price: 6.3, cat: "Sandwiches" },
  { id: "s02", name: "Egg & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s03", name: "Bacon & Egg Sandwich", price: 7.0, cat: "Sandwiches" },
  { id: "s04", name: "Ham & Cheese", price: 7.0, cat: "Sandwiches" },
  { id: "s05", name: "Ham Cheese & Tomato", price: 7.0, cat: "Sandwiches" },
  { id: "s06", name: "Ham Cheese & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s07", name: "Chicken & Mayo", price: 7.0, cat: "Sandwiches" },
  { id: "s08", name: "Chicken & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s09", name: "Beef Sweet Fruit Chutney", price: 7.0, cat: "Sandwiches" },
  { id: "s10", name: "Chicken & Avocado", price: 7.5, cat: "Sandwiches" },
  { id: "s12", name: "Egg & Mayo", price: 7.0, cat: "Sandwiches" },
  { id: "s13", name: "Ham & Egg", price: 7.0, cat: "Sandwiches" },
  { id: "s14", name: "Egg & Curry", price: 7.0, cat: "Sandwiches" },
  { id: "s15", name: "Egg Curry & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s16", name: "Chicken Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s17", name: "Ham Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s18", name: "Beef Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s19", name: "Salami Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s11", name: "Fruit Salad", price: 6.5, cat: "Sandwiches" },
  // —— Rolls & Buns ——
  { id: "r01", name: "Chicken Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r02", name: "Salami Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r03", name: "Bacon Lettuce Tomato Avocado", price: 7.9, cat: "Rolls & Buns" },
  { id: "r04", name: "Chicken Avocado Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r05", name: "Seafood Roll", price: 8.5, cat: "Rolls & Buns" },
  { id: "r06", name: "Bacon & Egg Bun", price: 7.9, cat: "Rolls & Buns" },
  { id: "r07", name: "Ham Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r08", name: "Beef Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r09", name: "Chicken Camembert Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r10", name: "Chicken Cranberry & Cheese Roll", price: 7.9, cat: "Rolls & Buns" },
  // —— Sweets ——
  { id: "d01", name: "Fresh Cream Donut", price: 4.9, cat: "Sweets" },
  { id: "d02", name: "Fresh Cream Chocolate Donut", price: 4.9, cat: "Sweets" },
  { id: "d03", name: "Fresh Cream Apple Donut", price: 4.9, cat: "Sweets" },
  { id: "d04", name: "Fresh Cream Nutella Donut", price: 4.9, cat: "Sweets" },
  { id: "d05", name: "Chocolate & Nutella Donut", price: 4.0, cat: "Sweets" },
  { id: "d06", name: "Apple Turnover", price: 4.7, cat: "Sweets" },
  { id: "d07", name: "Cream Apple Turnover", price: 5.5, cat: "Sweets" },
  { id: "d08", name: "Lamington", price: 4.9, cat: "Sweets" },
  { id: "d09", name: "Fresh Cream Lamington", price: 5.5, cat: "Sweets" },
  { id: "d10", name: "Choc Caramel Tim Tam Slice", price: 4.9, cat: "Sweets" },
  { id: "d11", name: "Caramel Slice", price: 4.9, cat: "Sweets" },
  { id: "d12", name: "Caramel Fudge Slice", price: 4.9, cat: "Sweets" },
  { id: "d13", name: "Caramel Oreo Slice", price: 4.9, cat: "Sweets" },
  { id: "d14", name: "Caramel Coconut Slice", price: 4.9, cat: "Sweets" },
  { id: "d15", name: "Ginger Slice", price: 4.9, cat: "Sweets" },
  { id: "d16", name: "Lemon Slice", price: 4.9, cat: "Sweets" },
  { id: "d17", name: "Lolly Slice", price: 4.9, cat: "Sweets" },
  { id: "d18", name: "Rocky Road", price: 4.9, cat: "Sweets" },
  { id: "d19", name: "White Chocolate Mars Slice", price: 4.9, cat: "Sweets" },
  { id: "d20", name: "Cookie & Cream Slice", price: 4.7, cat: "Sweets" },
  { id: "d21", name: "Chocolate Brownie", price: 4.9, cat: "Sweets" },
  { id: "d22", name: "Raspberry Cheesecake", price: 5.5, cat: "Sweets" },
  { id: "d23", name: "Carrot Cake", price: 5.0, cat: "Sweets" },
  { id: "d24", name: "Banana Cake", price: 5.0, cat: "Sweets" },
  { id: "d25", name: "Custard Tart", price: 4.5, cat: "Sweets" },
  { id: "d26", name: "Neenish Tart", price: 3.5, cat: "Sweets" },
  { id: "d27", name: "Yoyo", price: 3.5, cat: "Sweets" },
  { id: "d28", name: "Jam Tart", price: 3.0, cat: "Sweets" },
  { id: "d29", name: "Lemon Tart", price: 3.0, cat: "Sweets" },
  { id: "d30", name: "Gingerbread Man", price: 4.9, cat: "Sweets" },
  { id: "d31", name: "Happy Face Cookie", price: 4.9, cat: "Sweets" },
  { id: "d32", name: "Marshmallow Stick", price: 4.5, cat: "Sweets" },
  { id: "d33", name: "Choc Mud / Lemon Sorbet Log", price: 3.5, cat: "Sweets" },
  // —— Hot Food (prices from shop hot food menu board) ——
  { id: "h02", name: "Potato Cake", price: 1.6, cat: "Hot Food" },
  { id: "h11", name: "Small Dim Sim", price: 1.6, cat: "Hot Food" },
  { id: "h04", name: "Home Made Dim Sim", price: 2.9, cat: "Hot Food" },
  { id: "h12", name: "Chicken Sweet Chilli Tender", price: 2.5, cat: "Hot Food" },
  { id: "h06", name: "Chicken Wings", price: 2.5, cat: "Hot Food" },
  { id: "h13", name: "Seafood Stick", price: 2.0, cat: "Hot Food" },
  { id: "h07", name: "Butter Hot Dog", price: 3.7, cat: "Hot Food" },
  { id: "h14", name: "Lasagna Topper", price: 3.9, cat: "Hot Food" },
  { id: "h05", name: "Spring Roll", price: 3.5, cat: "Hot Food" },
  { id: "h10", name: "Hot Chips", price: 4.5, cat: "Hot Food" },
  { id: "h01", name: "Corn Dog", price: 3.5, cat: "Hot Food" },
  { id: "h15", name: "Bacon & Egg Toasted", price: 8.0, cat: "Hot Food" },
  { id: "h16", name: "Bacon & Cheese Toasted", price: 8.5, cat: "Hot Food" },
  { id: "h17", name: "Bacon & Egg Roll", price: 9.0, cat: "Hot Food" },
  { id: "h18", name: "Bacon & Cheese Roll", price: 9.5, cat: "Hot Food" },
  { id: "h19", name: "Sandwich / Roll (Ham, Beef, Chicken or Salami)", price: 7.0, cat: "Hot Food" },
  { id: "h08", name: "Kransky Sausage (Normal, Ham & Cheese, Spicy or Extra Spicy)", price: 6.0, cat: "Hot Food" },
  { id: "h03", name: "Hash Brown", price: 0, cat: "Hot Food" },
  { id: "h09", name: "Bacon Fritter", price: 0, cat: "Hot Food" },
  // —— Extras (hot food menu board) ——
  { id: "e01", name: "Cheese", price: 1.0, cat: "Extras" },
  { id: "e02", name: "Boiled Egg", price: 1.5, cat: "Extras" },
  { id: "e03", name: "Grilled Egg", price: 1.5, cat: "Extras" },
  { id: "e04", name: "Cooked Onion", price: 1.0, cat: "Extras" },
  { id: "e05", name: "Salad (per item)", price: 0.5, cat: "Extras" },
  { id: "e06", name: "Extra Meat Filling", price: 1.5, cat: "Extras" },
  { id: "e07", name: "Toasting", price: 0.5, cat: "Extras" },
  // —— Drinks (fridge price tags) ——
  // Nippy's cartons — $3.90
  { id: "k01", name: "Nippy's Iced Coffee (Carton)", price: 3.9, cat: "Drinks" },
  { id: "k02", name: "Nippy's Iced Chocolate (Carton)", price: 3.9, cat: "Drinks" },
  { id: "k03", name: "Nippy's Strawberry (Carton)", price: 3.9, cat: "Drinks" },
  { id: "k04", name: "Nippy's Honeycomb (Carton)", price: 3.9, cat: "Drinks" },
  // Water & slim cans — $4.00
  { id: "k05", name: "Mount Franklin Water 600ml", price: 4.0, cat: "Drinks" },
  { id: "k06", name: "V Energy Original 250ml", price: 4.0, cat: "Drinks" },
  { id: "k07", name: "V Energy Blue 250ml", price: 4.0, cat: "Drinks" },
  { id: "k08", name: "V Energy Raspberry 250ml", price: 4.0, cat: "Drinks" },
  { id: "k09", name: "V Energy Sugar-Free 250ml", price: 4.0, cat: "Drinks" },
  { id: "k10", name: "Coke Can 375ml", price: 4.0, cat: "Drinks" },
  { id: "k11", name: "Coke No Sugar Can 375ml", price: 4.0, cat: "Drinks" },
  { id: "k12", name: "Sprite Can 375ml", price: 4.0, cat: "Drinks" },
  { id: "k13", name: "Fanta Can 375ml", price: 4.0, cat: "Drinks" },
  { id: "k14", name: "Solo Can 375ml", price: 4.0, cat: "Drinks" },
  { id: "k15", name: "Kirks Can 375ml", price: 4.0, cat: "Drinks" },
  // BOSS coffee — $4.80
  { id: "k16", name: "BOSS Iced Long Black", price: 4.8, cat: "Drinks" },
  { id: "k17", name: "BOSS Iced Caramel Latte", price: 4.8, cat: "Drinks" },
  { id: "k18", name: "BOSS Iced Vanilla Latte", price: 4.8, cat: "Drinks" },
  { id: "k19", name: "BOSS Coffee Black (Bottle)", price: 5.0, cat: "Drinks" },
  { id: "k20", name: "BOSS Latte (Bottle)", price: 5.0, cat: "Drinks" },
  // 600ml soft drinks & juices — $4.90
  { id: "k21", name: "Coke 600ml", price: 4.9, cat: "Drinks" },
  { id: "k22", name: "Coke No Sugar 600ml", price: 4.9, cat: "Drinks" },
  { id: "k23", name: "Sprite 600ml", price: 4.9, cat: "Drinks" },
  { id: "k24", name: "Fanta Orange 600ml", price: 4.9, cat: "Drinks" },
  { id: "k25", name: "Fanta Grape 600ml", price: 4.9, cat: "Drinks" },
  { id: "k26", name: "Lift 600ml", price: 4.9, cat: "Drinks" },
  { id: "k27", name: "Kirks Pasito 600ml", price: 4.9, cat: "Drinks" },
  { id: "k28", name: "Kirks Portello 600ml", price: 4.9, cat: "Drinks" },
  { id: "k29", name: "Fuze Tea", price: 4.9, cat: "Drinks" },
  { id: "k30", name: "Vitamin Water", price: 4.9, cat: "Drinks" },
  { id: "k31", name: "Joe's Classics Pineapple", price: 4.9, cat: "Drinks" },
  { id: "k32", name: "Joe's Classics Apple & Guava", price: 4.9, cat: "Drinks" },
  { id: "k33", name: "Joe's Classics Mango & Banana", price: 4.9, cat: "Drinks" },
  { id: "k34", name: "Bundaberg Ginger Beer", price: 4.9, cat: "Drinks" },
  { id: "k35", name: "Bundaberg Guava", price: 4.9, cat: "Drinks" },
  // Energy & premium — $5.50
  { id: "k36", name: "Rockstar Original 500ml", price: 5.5, cat: "Drinks" },
  { id: "k37", name: "Rockstar Zero Sugar 500ml", price: 5.5, cat: "Drinks" },
  { id: "k38", name: "Rockstar Juiced 500ml", price: 5.5, cat: "Drinks" },
  { id: "k39", name: "Rockstar Strawberry & Cream", price: 5.5, cat: "Drinks" },
  { id: "k40", name: "Rockstar Tropical Guava", price: 5.5, cat: "Drinks" },
  { id: "k41", name: "Rockstar Strawberry Crush", price: 5.5, cat: "Drinks" },
  { id: "k42", name: "Rockstar Blueberry", price: 5.5, cat: "Drinks" },
  { id: "k43", name: "Monster Energy Original", price: 5.5, cat: "Drinks" },
  { id: "k44", name: "Monster Ultra", price: 5.5, cat: "Drinks" },
  { id: "k45", name: "Monster Mango Loco", price: 5.5, cat: "Drinks" },
  { id: "k46", name: "Calypso Island Wave Lemonade", price: 5.5, cat: "Drinks" },
  { id: "k47", name: "Calypso Ocean Blue Lemonade", price: 5.5, cat: "Drinks" },
  { id: "k48", name: "Calypso Strawberry Lemonade", price: 5.5, cat: "Drinks" },
  { id: "k49", name: "Calypso Kiwi Lemonade", price: 5.5, cat: "Drinks" },
  { id: "k50", name: "Calypso Grapeberry Lemonade", price: 5.5, cat: "Drinks" },
  { id: "k51", name: "Calypso Pineapple Peach Limeade", price: 5.5, cat: "Drinks" },
  { id: "k52", name: "Pump Berry Storm 750ml", price: 5.5, cat: "Drinks" },
  { id: "k53", name: "Pump Lime Rush 750ml", price: 5.5, cat: "Drinks" },
  { id: "k54", name: "Pump Spring Water 750ml", price: 5.5, cat: "Drinks" },
  // Sports drinks — $5.80
  { id: "k55", name: "G-Force Tropical Orange", price: 5.8, cat: "Drinks" },
  { id: "k56", name: "G-Force Green Apple", price: 5.8, cat: "Drinks" },
  { id: "k57", name: "G-Force Apple Blackcurrant", price: 5.8, cat: "Drinks" },
  { id: "k58", name: "G-Force Orange Mandarin", price: 5.8, cat: "Drinks" },
  // Celsius — $5.90 (2 for $9.00)
  { id: "k59", name: "Celsius Sparkling Orange", price: 5.9, cat: "Drinks" },
  { id: "k60", name: "Celsius Sparkling Kiwi Strawberry", price: 5.9, cat: "Drinks" },
  // Bottles & 1L — $6.00
  { id: "k61", name: "Nippy's Iced Coffee (Bottle)", price: 6.0, cat: "Drinks" },
  { id: "k62", name: "Nippy's Iced Chocolate (Bottle)", price: 6.0, cat: "Drinks" },
  { id: "k63", name: "Nippy's Protein Drink", price: 6.0, cat: "Drinks" },
  { id: "k64", name: "Large Milk 2L", price: 6.0, cat: "Drinks" },
  { id: "k65", name: "Ribena 500ml (2 for $6)", price: 6.0, cat: "Drinks" },
  { id: "k66", name: "Maximus Blue 1L", price: 6.0, cat: "Drinks" },
  { id: "k67", name: "Maximus Lemonade 1L", price: 6.0, cat: "Drinks" },
  { id: "k68", name: "Maximus Orange 1L", price: 6.0, cat: "Drinks" },
  { id: "k69", name: "Maximus Grape 1L", price: 6.0, cat: "Drinks" },
  { id: "k70", name: "Maximus Red (Suck It Up) 1L", price: 6.0, cat: "Drinks" },
  { id: "k71", name: "Powerade Mountain Blast", price: 6.0, cat: "Drinks" },
  { id: "k72", name: "Powerade Berry Ice", price: 6.0, cat: "Drinks" },
  { id: "k73", name: "Powerade Blackcurrant", price: 6.0, cat: "Drinks" },
  { id: "k74", name: "Powerade Gold Rush", price: 6.0, cat: "Drinks" },
  // V Energy large cans — $6.50
  { id: "k75", name: "V Energy Original 500ml", price: 6.5, cat: "Drinks" },
  { id: "k76", name: "V Energy Blue 500ml", price: 6.5, cat: "Drinks" },
  { id: "k77", name: "V Energy Raspberry Lemonade 500ml", price: 6.5, cat: "Drinks" },
  { id: "k78", name: "V Energy Tropical 500ml", price: 6.5, cat: "Drinks" },
  { id: "k79", name: "V Energy Grape 500ml", price: 6.5, cat: "Drinks" },
];

/** Old default prices — auto-upgrade saved menus when these still match. */
export const BOARD_PRICE_SYNC = {
  h02: [1.4],
  h11: [1.4],
  h01: [3.0],
};
