export const DEFAULT_MENU = [
  // —— Pies ——
  { id: "p01", name: "Steak Pie", price: 7.9, cat: "Pies" },
  { id: "p02", name: "Steak & Cheese", price: 7.9, cat: "Pies" },
  { id: "p03", name: "Steak & Pepper", price: 7.9, cat: "Pies" },
  { id: "p04", name: "Steak Mushroom", price: 7.9, cat: "Pies" },
  { id: "p05", name: "Steak Bacon Cheese", price: 7.9, cat: "Pies" },
  { id: "p06", name: "Steak Cheese Jalapeño", price: 7.9, cat: "Pies" },
  { id: "p07", name: "Steak Double Cheese", price: 8.7, cat: "Pies" },
  { id: "p08", name: "Mince & Cheese", price: 7.9, cat: "Pies" },
  { id: "p09", name: "Mince Double Cheese", price: 8.7, cat: "Pies" },
  { id: "p10", name: "Mince & Pepper", price: 7.9, cat: "Pies" },
  { id: "p11", name: "Chicken Mushroom", price: 7.9, cat: "Pies" },
  { id: "p12", name: "Chicken & Cheese", price: 7.9, cat: "Pies" },
  { id: "p13", name: "Butter Chicken", price: 7.9, cat: "Pies" },
  { id: "p14", name: "Bacon & Egg Pie", price: 7.9, cat: "Pies" },
  { id: "p15", name: "Double Happy", price: 8.5, cat: "Pies" },
  { id: "p16", name: "Small Mince Pie", price: 3.8, cat: "Pies" },
  { id: "p17", name: "Small Mince Potato", price: 3.8, cat: "Pies" },
  { id: "p18", name: "Sausage Roll", price: 6.0, cat: "Pies" },
  // —— Sandwiches ——
  { id: "s01", name: "Mixed Sandwiches", price: 6.3, cat: "Sandwiches" },
  { id: "s02", name: "Egg & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s03", name: "Bacon & Egg Sandwich", price: 7.0, cat: "Sandwiches" },
  { id: "s04", name: "Ham & Cheese", price: 7.0, cat: "Sandwiches" },
  { id: "s05", name: "Ham Cheese & Tomato", price: 7.0, cat: "Sandwiches" },
  { id: "s06", name: "Ham Cheese & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s07", name: "Chicken & Mayo", price: 7.0, cat: "Sandwiches" },
  { id: "s08", name: "Chicken & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s09", name: "Beef Sweet Fruit Chutney", price: 7.0, cat: "Sandwiches" },
  { id: "s10", name: "Chicken & Avocado", price: 7.5, cat: "Sandwiches" },
  { id: "s12", name: "Egg & Mayo", price: 7.0, cat: "Sandwiches" },
  { id: "s13", name: "Ham & Egg", price: 7.0, cat: "Sandwiches" },
  { id: "s14", name: "Egg & Curry", price: 7.0, cat: "Sandwiches" },
  { id: "s15", name: "Egg Curry & Lettuce", price: 7.0, cat: "Sandwiches" },
  { id: "s16", name: "Chicken Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s17", name: "Ham Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s18", name: "Beef Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s19", name: "Salami Salad Sandwich", price: 7.5, cat: "Sandwiches" },
  { id: "s11", name: "Fruit Salad", price: 6.5, cat: "Sandwiches" },
  // —— Rolls & Buns ——
  { id: "r01", name: "Chicken Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r02", name: "Salami Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r03", name: "Bacon Lettuce Tomato Avocado", price: 7.9, cat: "Rolls & Buns" },
  { id: "r04", name: "Chicken Avocado Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r05", name: "Seafood Roll", price: 8.5, cat: "Rolls & Buns" },
  { id: "r06", name: "Bacon & Egg Bun", price: 7.9, cat: "Rolls & Buns" },
  { id: "r07", name: "Ham Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r08", name: "Beef Salad Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r09", name: "Chicken Camembert Roll", price: 7.9, cat: "Rolls & Buns" },
  { id: "r10", name: "Chicken Cranberry & Cheese Roll", price: 7.9, cat: "Rolls & Buns" },
  // —— Sweets ——
  { id: "d01", name: "Fresh Cream Donut", price: 4.9, cat: "Sweets" },
  { id: "d02", name: "Fresh Cream Chocolate Donut", price: 4.9, cat: "Sweets" },
  { id: "d03", name: "Fresh Cream Apple Donut", price: 4.9, cat: "Sweets" },
  { id: "d04", name: "Fresh Cream Nutella Donut", price: 4.9, cat: "Sweets" },
  { id: "d05", name: "Chocolate & Nutella Donut", price: 4.0, cat: "Sweets" },
  { id: "d06", name: "Apple Turnover", price: 4.7, cat: "Sweets" },
  { id: "d07", name: "Cream Apple Turnover", price: 5.5, cat: "Sweets" },
  { id: "d08", name: "Lamington", price: 4.9, cat: "Sweets" },
  { id: "d09", name: "Fresh Cream Lamington", price: 5.5, cat: "Sweets" },
  { id: "d10", name: "Choc Caramel Tim Tam Slice", price: 4.9, cat: "Sweets" },
  { id: "d11", name: "Caramel Slice", price: 4.9, cat: "Sweets" },
  { id: "d12", name: "Caramel Fudge Slice", price: 4.9, cat: "Sweets" },
  { id: "d13", name: "Caramel Oreo Slice", price: 4.9, cat: "Sweets" },
  { id: "d14", name: "Caramel Coconut Slice", price: 4.9, cat: "Sweets" },
  { id: "d15", name: "Ginger Slice", price: 4.9, cat: "Sweets" },
  { id: "d16", name: "Lemon Slice", price: 4.9, cat: "Sweets" },
  { id: "d17", name: "Lolly Slice", price: 4.9, cat: "Sweets" },
  { id: "d18", name: "Rocky Road", price: 4.9, cat: "Sweets" },
  { id: "d19", name: "White Chocolate Mars Slice", price: 4.9, cat: "Sweets" },
  { id: "d20", name: "Cookie & Cream Slice", price: 4.7, cat: "Sweets" },
  { id: "d21", name: "Chocolate Brownie", price: 4.9, cat: "Sweets" },
  { id: "d22", name: "Raspberry Cheesecake", price: 5.5, cat: "Sweets" },
  { id: "d23", name: "Carrot Cake", price: 5.0, cat: "Sweets" },
  { id: "d24", name: "Banana Cake", price: 5.0, cat: "Sweets" },
  { id: "d25", name: "Custard Tart", price: 4.5, cat: "Sweets" },
  { id: "d26", name: "Neenish Tart", price: 3.5, cat: "Sweets" },
  { id: "d27", name: "Yoyo", price: 3.5, cat: "Sweets" },
  { id: "d28", name: "Jam Tart", price: 3.0, cat: "Sweets" },
  { id: "d29", name: "Lemon Tart", price: 3.0, cat: "Sweets" },
  { id: "d30", name: "Gingerbread Man", price: 4.9, cat: "Sweets" },
  { id: "d31", name: "Happy Face Cookie", price: 4.9, cat: "Sweets" },
  { id: "d32", name: "Marshmallow Stick", price: 4.5, cat: "Sweets" },
  { id: "d33", name: "Choc Mud / Lemon Sorbet Log", price: 3.5, cat: "Sweets" },
  // —— Hot Food (prices read from the menu board photo — double-check, board may be old) ——
  { id: "h01", name: "Corn Dog", price: 3.0, cat: "Hot Food" },
  { id: "h02", name: "Potato Cake", price: 1.4, cat: "Hot Food" },
  { id: "h03", name: "Hash Brown", price: 0, cat: "Hot Food" },
  { id: "h04", name: "Home Made Dim Sim", price: 2.9, cat: "Hot Food" },
  { id: "h11", name: "Small Dim Sim", price: 1.4, cat: "Hot Food" },
  { id: "h05", name: "Spring Roll", price: 3.5, cat: "Hot Food" },
  { id: "h06", name: "Chicken Wings", price: 2.5, cat: "Hot Food" },
  { id: "h12", name: "Chicken Sweet Chilli Tender", price: 2.5, cat: "Hot Food" },
  { id: "h13", name: "Seafood Stick", price: 2.0, cat: "Hot Food" },
  { id: "h07", name: "Butter Hot Dog", price: 3.7, cat: "Hot Food" },
  { id: "h08", name: "Kransky Sausage", price: 6.0, cat: "Hot Food" },
  { id: "h14", name: "Lasagna Topper", price: 3.9, cat: "Hot Food" },
  { id: "h10", name: "Hot Chips", price: 4.5, cat: "Hot Food" },
  { id: "h09", name: "Bacon Fritter", price: 0, cat: "Hot Food" },
  { id: "h15", name: "Bacon & Egg Toasted", price: 8.0, cat: "Hot Food" },
  { id: "h16", name: "Bacon & Cheese Toasted", price: 8.5, cat: "Hot Food" },
  { id: "h17", name: "Bacon & Egg Roll (Hot)", price: 9.0, cat: "Hot Food" },
  { id: "h18", name: "Bacon & Cheese Roll (Hot)", price: 9.5, cat: "Hot Food" },
  // —— Drinks (set price once in Edit) ——
  { id: "k01", name: "Soft Drink Can", price: 0, cat: "Drinks" },
  { id: "k02", name: "L&P Can", price: 0, cat: "Drinks" },
  { id: "k03", name: "Soft Drink Bottle 600ml", price: 0, cat: "Drinks" },
  { id: "k04", name: "Water Bottle", price: 0, cat: "Drinks" },
  { id: "k05", name: "Coffee", price: 0, cat: "Drinks" },
  { id: "k06", name: "Flavoured Milk", price: 0, cat: "Drinks" },
];
